version: '3'

services:

  server:

    build: docGenerator/

    command: java -jar backend.jar

    ports:
      - 8080:8080

  client:

    build: generator-client

    command: npm start

    ports:
      - 3000:3000

    depends_on:
      - server