version: '3'

services:

  server:

    build: server/
    # image: urbel/docgener-server

    command: java -jar backend.jar

    ports:
      - 8080:8080

  client:

    build: client/

    # image: urbel/docgener-client

    command: npm start

    ports:
      - 3000:3000

    depends_on:
      - server
